// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxgwbjfpmvetcsbkibot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4Z3diamZwbXZldGNzYmtpYm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDMzNjcsImV4cCI6MjA2OTIxOTM2N30.s5z5DnUCG3KiPRAvEk6Fs0nNdFcL67hluD8CmEAhq48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});